apiVersion: v1
kind: ConfigMap
metadata:
  name: nginxconfig
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    http {
        server {
            listen       80;
            server_name  localhost;

            location / {
                root   /usr/share/nginx/html;
                index  index.html index.htm;
            }

            error_page   500 502 503 504  /50x.html;
            location = /50x.html {
                root   /usr/share/nginx/html;
            }
        }
    }

  index.html: |
    <html>
    <head>
    <title>Welcome to nginx!</title>
    </head>
    <body>
    <h1>Welcome to nginx!</h1>
    </body>
    </html>
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 80
        volumeMounts:
        - name: nginxconfig
          mountPath: /etc/nginx
          # subPath: nginx.conf
        - name: nginxconfig
          mountPath: /usr/share/nginx/html
          # subPath: index.html
      volumes:
      - name: nginxconfig
        configMap:
          name: nginxconfig
          items:
          - key: nginx.conf
            path: nginx.conf
          - key: index.html
            path: index.html
---
apiVersion: v1
kind: Service
metadata:
  name: nginx
spec:
  selector:
    app: nginx
  ports:
  - protocol: TCP
    port: 80
    targetPort: 80
